# Generated by Django 4.0.10 on 2023-03-27 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_review_delete_productreview'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='font',
            field=models.CharField(default=False, max_length=50),
        ),
    ]
